"""user llm settings

Revision ID: 3c1f89b3bc03
Revises: ee4e9237d11c
Create Date: 2026-07-28 12:00:12.040452

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '3c1f89b3bc03'
down_revision: str | None = 'ee4e9237d11c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_api_key_enc', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('llm_model', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('llm_offline', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('llm_offline')
        batch_op.drop_column('llm_model')
        batch_op.drop_column('llm_api_key_enc')

    # ### end Alembic commands ###
